---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-web
  labels:
    app: events-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events-web
  template:
    metadata:
      labels:
        app: events-web
    spec:
      containers:
      - name: events-web
        image: gcr.io/myproject-278611/spring-frontend:V_3
        env:
        - name: PORT
          value: "8085"
        - name: SERVER
          value: "http://events-data-service:8082"
        ports:
        - containerPort: 8085
          name: "events-port"
        livenessProbe:
          httpGet:
            path: /
            port: 8085
          initialDelaySeconds: 60
          periodSeconds: 60

---
apiVersion: v1
kind: Service
metadata: 
  name: events-web-service
spec: 
  ports: 
     -  port: 8085
        protocol: TCP
        targetPort: 8085
  selector: 
    app: events-web
  type: LoadBalancer

---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: events-web-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v2beta1
    kind: Deployment
    name: events-web
  minReplicas: 1
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 60
